/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sv.udb.vistas;

import com.sv.udb.controlador.CtrlEspecies;
import com.sv.udb.modelo.Especies;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DanielWilfredo
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        llenarComboBox();
    }
    private void llenarComboBox()
    {
        try
        {
            DefaultComboBoxModel<Especies> model = new DefaultComboBoxModel<>();//            
            for(Especies temp : new CtrlEspecies().consTodo())
            {
                model.addElement(temp);
            }
            this.cmbrefeser.setModel((DefaultComboBoxModel)model);
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnguardar = new javax.swing.JButton();
        btnmodificar = new javax.swing.JButton();
        btnconsultar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtcodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtdesc = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblespecies = new javax.swing.JTable();
        cmbrefeser = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Especies"));

        btnguardar.setText("Guardar");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });

        btnmodificar.setText("Modificar");
        btnmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificarActionPerformed(evt);
            }
        });

        btnconsultar.setText("Consultar");
        btnconsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconsultarActionPerformed(evt);
            }
        });

        btneliminar.setText("Eliminar");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        jLabel1.setText("Codigo ser:");

        txtcodigo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtcodigo.setEnabled(false);

        jLabel2.setText("Nombre ser:");

        txtnombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel3.setText("Descripcion ser:");

        txtdesc.setColumns(20);
        txtdesc.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtdesc.setRows(5);
        jScrollPane1.setViewportView(txtdesc);

        jLabel4.setText("Referencia ser:");

        tblespecies.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo Sere", "Nombre ser", "Pertenece a", "Descripcion Sere"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblespecies.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblespeciesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblespecies);
        if (tblespecies.getColumnModel().getColumnCount() > 0) {
            tblespecies.getColumnModel().getColumn(0).setResizable(false);
            tblespecies.getColumnModel().getColumn(1).setResizable(false);
            tblespecies.getColumnModel().getColumn(2).setResizable(false);
            tblespecies.getColumnModel().getColumn(3).setResizable(false);
        }

        cmbrefeser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Si desea modificar un registro padre");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Seleccione Reino Padre en el cmb");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cmbrefeser, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtcodigo)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtnombre)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1))
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnmodificar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnconsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btneliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbrefeser, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnmodificar, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                        .addComponent(btnconsultar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btneliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnguardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnconsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconsultarActionPerformed
cargarTabla();
    }//GEN-LAST:event_btnconsultarActionPerformed
private void cargarTabla()
{
    try
        {
            DefaultTableModel model = (DefaultTableModel)this.tblespecies.getModel();
            while(model.getRowCount()>0){model.removeRow(0);} //Limpiar modelo
            
            for(Especies temp : new CtrlEspecies().consTodo())
            {
                if(temp.getCodiEspe()!=0)
                {
                    model.addRow(new Object[]{temp.getCodiEspe(),  temp, temp.getNombRefeEspe() , temp.getDescEspe()});
                }
            }
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
}
    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        try
        {
            if(txtnombre.getText().isEmpty())
            {
                 throw new Exception("Ingrese el nombre del ser vivo");
            }
            if(txtdesc.getText().isEmpty())
            {
                 throw new Exception("Ingrese una descripcion");
            }
            Especies obje = new Especies();
            Especies objeEspe  = (Especies)this.cmbrefeser.getSelectedItem();
            obje.setDescEspe(this.txtdesc.getText());
            obje.setNombEspe(this.txtnombre.getText());
            obje.setCodiRefeEspe(objeEspe.getCodiEspe());
            if(cmbrefeser.getSelectedIndex() == 0)
            {
                if(new CtrlEspecies().guar2(obje))
                {
                    JOptionPane.showMessageDialog(this, "Datos guardados");
                    cargarTabla();
                    llenarComboBox();
                     txtcodigo.setText("");
                    txtnombre.setText("");
                    txtdesc.setText("");
                    txtnombre.requestFocus();
                    cmbrefeser.setSelectedIndex(0);
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "Error al guardar los datos");
                     txtcodigo.setText("");
                    txtnombre.setText("");
                    txtdesc.setText("");
                    txtnombre.requestFocus();
                    cmbrefeser.setSelectedIndex(0);
                }
            }
            else
            {
                if(new CtrlEspecies().guar(obje))
                {
                    JOptionPane.showMessageDialog(this, "Datos guardados");
                    llenarComboBox();
                    txtcodigo.setText("");
                    txtnombre.setText("");
                    txtdesc.setText("");
                    txtnombre.requestFocus();
                    cmbrefeser.setSelectedIndex(0);
                    cargarTabla();
                    
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "Error al guardar los datos");
                }
            }
            
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_btnguardarActionPerformed

    private void tblespeciesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblespeciesMouseClicked
        try {
             int fila = this.tblespecies.getSelectedRow();
        if(fila >= 1)
        {
            Especies obje = (Especies)this.tblespecies.getValueAt(fila, 1);
            Especies espe = (Especies)new CtrlEspecies().consUno(obje.getCodiRefeEspe());
            cmbrefeser.setEditable(true);
            cmbrefeser.setSelectedItem(espe);
            cmbrefeser.setEditable(false);
            this.txtcodigo.setText(String.valueOf(obje.getCodiEspe()));
            this.txtnombre.setText(obje.getNombEspe());
            this.txtdesc.setText(String.valueOf(obje.getDescEspe()));
        }
        } catch (Exception e) {
            System.err.println("Error:" +e.getMessage());
        }
                
    }//GEN-LAST:event_tblespeciesMouseClicked

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
         int vali = JOptionPane.showConfirmDialog(this, "Decea eliminar este registro");
        if(vali == 1 || vali == 2 || vali == -1)
        {
            
        }
        else
        {
            try
            {
                if(txtcodigo.getText().isEmpty())
                {
                    throw new Exception("Seleccione un registro a eliminar");
                }
                Especies obje = new Especies();
                obje.setCodiEspe(Integer.parseInt(this.txtcodigo.getText()));
                if(new CtrlEspecies().elim(obje))
                {
                    JOptionPane.showMessageDialog(this, "Datos Eliminados");
                    txtcodigo.setText("");
                    txtnombre.setText("");
                    txtdesc.setText("");
                    txtnombre.requestFocus();
                    cmbrefeser.setSelectedIndex(0);
                   cargarTabla();
                   llenarComboBox();
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "No se puede Eliminar una tabla dependiente");
                }
            }
            catch(Exception ex)
            {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        }
    }//GEN-LAST:event_btneliminarActionPerformed

    private void btnmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificarActionPerformed
        try
        {
            if(txtnombre.getText().isEmpty())
            {
                 throw new Exception("Ingrese el nombre del ser vivo");
            }
            if(txtdesc.getText().isEmpty())
            {
                 throw new Exception("Ingrese una descripcion");
            }
            if(txtcodigo.getText().isEmpty())
            {
                throw new Exception("Seleccione un registro a modificar");
            }
            Especies obje = new Especies();
            Especies objeEspe  = (Especies)this.cmbrefeser.getSelectedItem();
            obje.setNombEspe(this.txtnombre.getText());
            obje.setDescEspe(this.txtdesc.getText());
           obje.setCodiRefeEspe(objeEspe.getCodiEspe());
            obje.setCodiEspe(Integer.parseInt(this.txtcodigo.getText()));
   if(this.cmbrefeser.getSelectedIndex() == 0 )
   {
       if(new CtrlEspecies().modi2(obje))
                {
                    JOptionPane.showMessageDialog(this, "Datos modificados");
                   txtcodigo.setText("");
                    txtnombre.setText("");
                    txtdesc.setText("");
                    txtnombre.requestFocus();
                    llenarComboBox();
                    cargarTabla();
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "Error al modificar");
                }
   }
   else
   {
       if(new CtrlEspecies().modi(obje))
                {
                    JOptionPane.showMessageDialog(this, "Datos modificados");
                   txtcodigo.setText("");
                    txtnombre.setText("");
                    txtdesc.setText("");
                    txtnombre.requestFocus();
                    llenarComboBox();
                    cargarTabla();
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "Error al modificar");
                }
   }
             
                     
            
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_btnmodificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnconsultar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnmodificar;
    private javax.swing.JComboBox<String> cmbrefeser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblespecies;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextArea txtdesc;
    private javax.swing.JTextField txtnombre;
    // End of variables declaration//GEN-END:variables
}
